"use client";

import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatCompactCurrency, formatCurrency } from "@/lib/formatters";
import type { RevenuePoint } from "@/types/analytics";

export function RevenueOverTimeChart({ data, totalRevenue, orders }: { data: RevenuePoint[]; totalRevenue: number; orders: number }) {
  if (data.length === 0) return <p className="flex h-72 items-center justify-center text-sm text-muted-foreground">No revenue points available.</p>;
  return <figure><figcaption className="sr-only">Net sales for the selected period totaled {formatCurrency(totalRevenue)} across {orders} orders created.</figcaption><div role="img" aria-label={`Daily net sales chart totaling ${formatCurrency(totalRevenue)}`} className="h-[280px] w-full sm:h-[320px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 12, right: 4, left: -8, bottom: 0 }}><defs><linearGradient id="analyticsRevenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4f46e5" stopOpacity={0.2} /><stop offset="100%" stopColor="#4f46e5" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef0f3" strokeDasharray="3 3" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#667085", fontSize: 11 }} minTickGap={34} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#667085", fontSize: 11 }} tickFormatter={formatCompactCurrency} width={58} /><Tooltip formatter={(value) => [formatCurrency(Number(value)), "Net sales"]} labelFormatter={(label) => String(label)} contentStyle={{ border: "1px solid #e4e7ec", borderRadius: "10px", boxShadow: "0 8px 24px rgba(15, 23, 42, 0.08)", fontSize: "12px" }} cursor={{ stroke: "#a5b4fc", strokeDasharray: "4 4" }} /><Area isAnimationActive={false} type="linear" dataKey="revenue" stroke="#4f46e5" strokeWidth={2} fill="url(#analyticsRevenueFill)" activeDot={{ r: 4, fill: "#4f46e5", stroke: "#ffffff", strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div></figure>;
}
