import { ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { formatCurrency } from "@/lib/formatters";
import type { Product } from "@/types/product";
import { getStockHealth } from "../lib/inventory";
import { getProductCategoryLabel } from "../lib/product-labels";
import { InventoryIndicator } from "./inventory-indicator";
import { ProductStatusBadge, StockHealthBadge } from "./product-badges";
import { ProductThumbnail } from "./product-thumbnail";

function detailHref(productId: string, returnUrl: string) { return { pathname: `/products/${productId}`, query: { returnTo: returnUrl } }; }

export function ProductsCollection({ products, returnUrl }: { products: Product[]; returnUrl: string }) {
  return <div className="overflow-hidden rounded-card border border-border bg-card">
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1000px] text-left text-sm"><caption className="sr-only">Product catalog</caption><thead><tr className="border-b border-border bg-slate-50/70 text-xs font-medium uppercase tracking-wide text-muted-foreground"><th scope="col" className="px-5 py-3">Product</th><th scope="col" className="px-5 py-3">Category</th><th scope="col" className="px-5 py-3">Status</th><th scope="col" className="px-5 py-3 text-right">Price</th><th scope="col" className="px-5 py-3">Inventory</th><th scope="col" className="px-5 py-3 text-right">Sold</th><th scope="col" className="px-5 py-3 text-right">Revenue</th><th scope="col" className="px-5 py-3"><span className="sr-only">Action</span></th></tr></thead>
      <tbody className="divide-y divide-border">{products.map((product) => <tr key={product.id} className="transition-colors hover:bg-slate-50/70"><th scope="row" className="px-5 py-4"><div className="flex items-center gap-3"><ProductThumbnail category={product.category} /><div className="min-w-0"><Link href={detailHref(product.id, returnUrl)} className="font-medium text-slate-900 hover:text-primary focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">{product.name}</Link><p className="mt-0.5 text-xs font-normal text-muted-foreground">{product.sku}</p></div></div></th><td className="px-5 py-4 text-slate-700">{getProductCategoryLabel(product.category)}</td><td className="px-5 py-4"><ProductStatusBadge status={product.status} /></td><td className="px-5 py-4 text-right font-medium tabular-nums text-slate-900">{formatCurrency(product.price)}</td><td className="px-5 py-4"><InventoryIndicator product={product} compact /></td><td className="px-5 py-4 text-right tabular-nums text-slate-700">{product.unitsSold}</td><td className="px-5 py-4 text-right font-semibold tabular-nums text-slate-900">{formatCurrency(product.revenue)}</td><td className="px-5 py-4"><Link href={detailHref(product.id, returnUrl)} aria-label={`View product ${product.name}`} className="inline-flex size-8 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-muted hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><ArrowUpRight aria-hidden="true" className="size-4" /></Link></td></tr>)}</tbody>
    </table></div>
    <ul aria-label="Product catalog" className="divide-y divide-border md:hidden">{products.map((product) => { const health = getStockHealth(product); return <li key={product.id} className="p-4"><div className="flex items-start gap-3"><ProductThumbnail category={product.category} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><Link href={detailHref(product.id, returnUrl)} className="block truncate text-sm font-semibold text-slate-900 hover:text-primary">{product.name}</Link><p className="mt-0.5 text-xs text-muted-foreground">{product.sku} · {getProductCategoryLabel(product.category)}</p></div><p className="shrink-0 text-sm font-semibold tabular-nums text-slate-900">{formatCurrency(product.price)}</p></div><div className="mt-3 flex flex-wrap items-center gap-2"><ProductStatusBadge status={product.status} /><StockHealthBadge health={health} /></div></div></div><div className="mt-4 flex items-end justify-between border-t border-border pt-3"><div><p className="text-xs font-medium text-slate-700">{product.inventory.available} available</p><p className="mt-1 text-xs text-muted-foreground">{product.unitsSold} units sold</p></div><Link href={detailHref(product.id, returnUrl)} className="inline-flex items-center gap-1 text-xs font-medium text-primary focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">View product <ArrowUpRight aria-hidden="true" className="size-3.5" /></Link></div></li>; })}</ul>
  </div>;
}
