"use client";

import { Search, SlidersHorizontal, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { useDebouncedValue } from "@/hooks/use-debounced-value";
import { campaignChannels, campaignStatuses, type CampaignChannel, type CampaignStatus } from "@/types/campaign";
import { campaignChannelLabels, campaignStatusLabels } from "../lib/campaign-labels";
import type { CampaignSort, GetCampaignsParams } from "../types";

interface Props { params: GetCampaignsParams; hasActiveFilters: boolean; onUpdate: (updates: Partial<Pick<GetCampaignsParams, "search" | "status" | "channel" | "sort">>, replace?: boolean) => void; onClear: () => void }
const selectClassName = "h-10 w-full rounded-lg border border-border bg-card px-3 text-sm text-slate-700 outline-none transition-colors hover:bg-muted focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2";

export function CampaignFilters({ params, hasActiveFilters, onUpdate, onClear }: Props) {
  const [searchState, setSearchState] = useState({ source: params.search, draft: params.search });
  if (searchState.source !== params.search) setSearchState({ source: params.search, draft: params.search });
  const searchValue = searchState.source === params.search ? searchState.draft : params.search;
  const debouncedSearch = useDebouncedValue(searchValue, 350);
  useEffect(() => { if (debouncedSearch !== params.search) onUpdate({ search: debouncedSearch }, true); }, [debouncedSearch, onUpdate, params.search]);
  return <section aria-label="Campaign filters" className="rounded-card border border-border bg-card p-4 sm:p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-end"><label className="block min-w-0 flex-1"><span className="mb-1.5 block text-xs font-medium text-slate-700">Search campaigns</span><span className="relative block"><Search aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input type="search" value={searchValue} onChange={(event) => { const value = event.target.value; setSearchState({ source: params.search, draft: value }); if (!value) onUpdate({ search: "" }, true); }} placeholder="Search campaigns..." className="h-10 w-full rounded-lg border border-border bg-card pl-9 pr-3 text-sm outline-none placeholder:text-slate-400 focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2" /></span></label><div className="grid gap-3 sm:grid-cols-3 xl:w-[690px]"><label><span className="mb-1.5 block text-xs font-medium text-slate-700">Status</span><select value={params.status} onChange={(event) => onUpdate({ status: event.target.value as CampaignStatus | "all" })} className={selectClassName}><option value="all">All statuses</option>{campaignStatuses.map((status) => <option key={status} value={status}>{campaignStatusLabels[status]}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-medium text-slate-700">Channel</span><select value={params.channel} onChange={(event) => onUpdate({ channel: event.target.value as CampaignChannel | "all" })} className={selectClassName}><option value="all">All channels</option>{campaignChannels.map((channel) => <option key={channel} value={channel}>{campaignChannelLabels[channel]}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-medium text-slate-700">Sort by</span><select value={params.sort} onChange={(event) => onUpdate({ sort: event.target.value as CampaignSort })} className={selectClassName}><option value="recent">Recently started</option><option value="oldest">Oldest</option><option value="highest-revenue">Highest revenue</option><option value="highest-roas">Highest ROAS</option><option value="highest-spend">Highest spend</option><option value="lowest-spend">Lowest spend</option><option value="name-asc">Name A–Z</option></select></label></div></div>{hasActiveFilters && <div className="mt-4 flex items-center justify-between border-t border-border pt-4"><span className="inline-flex items-center gap-1.5 text-xs font-medium text-primary"><SlidersHorizontal aria-hidden="true" className="size-3.5" /> Filters applied</span><Button type="button" variant="ghost" onClick={onClear} className="h-8 px-2"><X aria-hidden="true" className="size-4" /> Clear filters</Button></div>}</section>;
}
