import { ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { formatCurrency, formatDate } from "@/lib/formatters";
import type { Customer } from "@/types/customer";
import { acquisitionChannelLabels } from "../lib/customer-labels";
import { CustomerAvatar } from "./customer-avatar";
import { CustomerSegmentBadge } from "./customer-segment-badge";

function detailHref(customerId: string, returnUrl: string) {
  return { pathname: `/customers/${customerId}`, query: { returnTo: returnUrl } };
}

function recencyLabel(days: number): string {
  if (days === 0) return "Today";
  if (days === 1) return "1 day ago";
  return `${days} days ago`;
}

export function CustomersCollection({ customers, returnUrl }: { customers: Customer[]; returnUrl: string }) {
  return <div className="overflow-hidden rounded-card border border-border bg-card">
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1020px] text-left text-sm"><caption className="sr-only">Customer relationships and value</caption><thead><tr className="border-b border-border bg-slate-50/70 text-xs font-medium uppercase tracking-wide text-muted-foreground"><th scope="col" className="px-5 py-3">Customer</th><th scope="col" className="px-5 py-3">Segment</th><th scope="col" className="px-5 py-3 text-center">Orders</th><th scope="col" className="px-5 py-3 text-right">Lifetime value</th><th scope="col" className="px-5 py-3 text-right">Average order</th><th scope="col" className="px-5 py-3">Last order</th><th scope="col" className="px-5 py-3">Acquisition</th><th scope="col" className="px-5 py-3"><span className="sr-only">Action</span></th></tr></thead>
      <tbody className="divide-y divide-border">{customers.map((customer) => <tr key={customer.id} className="transition-colors hover:bg-slate-50/70"><th scope="row" className="px-5 py-4"><div className="flex min-w-0 items-center gap-3"><CustomerAvatar name={customer.name} customerId={customer.id} /><div className="min-w-0"><Link href={detailHref(customer.id, returnUrl)} className="block truncate font-medium text-slate-900 hover:text-primary focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">{customer.name}</Link><p className="mt-0.5 max-w-56 truncate text-xs font-normal text-muted-foreground">{customer.email}</p></div></div></th><td className="px-5 py-4"><CustomerSegmentBadge segment={customer.segment} /></td><td className="px-5 py-4 text-center tabular-nums text-slate-700">{customer.ordersCount}</td><td className="px-5 py-4 text-right font-semibold tabular-nums text-slate-900">{formatCurrency(customer.lifetimeValue)}</td><td className="px-5 py-4 text-right tabular-nums text-slate-700">{formatCurrency(customer.averageOrderValue)}</td><td className="px-5 py-4"><p className="text-slate-700">{formatDate(customer.lastOrderAt)}</p><p className="mt-0.5 text-xs text-muted-foreground">{recencyLabel(customer.daysSinceLastOrder)}</p></td><td className="px-5 py-4 text-slate-700">{acquisitionChannelLabels[customer.acquisitionChannel]}</td><td className="px-5 py-4"><Link href={detailHref(customer.id, returnUrl)} aria-label={`View customer ${customer.name}`} className="inline-flex size-8 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-muted hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><ArrowUpRight aria-hidden="true" className="size-4" /></Link></td></tr>)}</tbody>
    </table></div>
    <ul aria-label="Customer relationships and value" className="divide-y divide-border md:hidden">{customers.map((customer) => <li key={customer.id} className="p-4"><div className="flex items-start gap-3"><CustomerAvatar name={customer.name} customerId={customer.id} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><Link href={detailHref(customer.id, returnUrl)} className="block truncate text-sm font-semibold text-slate-900 hover:text-primary focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">{customer.name}</Link><p className="mt-0.5 truncate text-xs text-muted-foreground">{customer.email}</p></div><CustomerSegmentBadge segment={customer.segment} /></div></div></div><dl className="mt-4 grid grid-cols-3 gap-2 border-t border-border pt-3"><div><dt className="text-[11px] text-muted-foreground">Orders</dt><dd className="mt-1 text-sm font-semibold tabular-nums text-slate-900">{customer.ordersCount}</dd></div><div><dt className="text-[11px] text-muted-foreground">Lifetime value</dt><dd className="mt-1 text-sm font-semibold tabular-nums text-slate-900">{formatCurrency(customer.lifetimeValue)}</dd></div><div><dt className="text-[11px] text-muted-foreground">Last order</dt><dd className="mt-1 text-xs font-medium text-slate-800">{formatDate(customer.lastOrderAt)}</dd></div></dl><div className="mt-3 flex items-center justify-between"><p className="truncate text-xs text-muted-foreground">{acquisitionChannelLabels[customer.acquisitionChannel]}</p><Link href={detailHref(customer.id, returnUrl)} className="inline-flex items-center gap-1 text-xs font-medium text-primary focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">View customer <ArrowUpRight aria-hidden="true" className="size-3.5" /></Link></div></li>)}</ul>
  </div>;
}
